import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useState, useEffect } from 'react'
import { useCookies } from 'react-cookie'
import axios from 'axios'
import { useRouter } from "next/router";

import Back from '../../public/Back.png'

const inter = Inter({ subsets: ['latin'] })

export default function Login() {
  const [username, setUsername] = useState();
  const [password, setPassword] = useState();
  const [message, setMessage] = useState();
  const [cookies, setCookies] = useCookies();
  const router = useRouter();

  const login = async (e) => {
    e.preventDefault();
    if (username === '' || password === '') {
      setMessage('Terdapat kolom yang kosong.');
    } else {
      await axios.post(`${process.env.NEXT_PUBLIC_VASCOMM_TEST_API}/login`, {
        username: username,
        password: password
      }).then(response => {
        console.log(response)
        if (response.data.error) {
          setMessage(response.data.error);
        } else {
          setCookies("vascomm_api_key", response.data.api_key);
        }
      })
    }
  }

  useEffect(() => {
    if (cookies.vascomm_api_key) {
      router.push("/");
    }
  })

  return (
    <>
      <Head>
        <title>Vascomm Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <div className='row justify-content-center'>
          <div className='col-md-4 col-md-offset-4 border border-secondary mt-3 mb-3'>
            <br></br>
            <h4 className='text-center'>Login</h4>
            <hr></hr>
            <a href='/' className='left ms-2'><Image alt='Back' src={Back} /></a>
            <br></br>
            <br></br>
            <div className='form-group'>
                <label for='username' className='left'>Username</label>
                <input type='text' className='form-control' name='username' onChange={e => setUsername(e.target.value)} />
            </div>
            <div className='form-group'>
                <label for='password' className='left'>Password</label>
                <input type='password' className='form-control' name='password' onChange={e => setPassword(e.target.value)} />
            </div>
            <br></br>
            <p className='text-danger text-center'>{message}</p>
            <div className='form-group text-center'>
                <button className='btn btn-block btn-primary' onClick={login}>Login</button>
            </div>
            <br></br>
          </div>
          <a href='/auth/register' className='text-center'>Don't have an account? Register here</a>
        </div>
      </div>
    </>
  )
}
