import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useState, useEffect } from 'react'
import { useCookies } from 'react-cookie'
import axios from 'axios'
import { useRouter } from "next/router";

import Back from '../../public/Back.png'

const inter = Inter({ subsets: ['latin'] })

export default function Register() {
  const [username, setUsername] = useState();
  const [password, setPassword] = useState();
  const [foto, setFoto] = useState();
  const [failMessage, setFailMessage] = useState();
  const [successMessage, setSuccessMessage] = useState();
  const [cookies] = useCookies();
  const router = useRouter();

  const register = async (e) => {
    e.preventDefault();
    if (username === '' || password === '' || foto === '') {
      setFailMessage('Terdapat kolom yang kosong.');
      setSuccessMessage('');
    } else {
      await axios.post(`${process.env.NEXT_PUBLIC_VASCOMM_TEST_API}/register`, {
        username: username,
        password: password,
        foto: foto
      }, {
        headers: {
            'Content-Type': 'multipart/form-data'
        }
      }).then(response => {
        if (!response.data.error) {
            setSuccessMessage("Registrasi berhasil. Akun Anda akan segera diverifikasi.");
            setFailMessage('');
        } else {
            setFailMessage(response.data.error);
            setSuccessMessage('');
        }
      });
    }
  }

  useEffect(() =>{
    if (cookies.vascomm_api_key) {
      router.push("/");
    }
  })

  return (
    <>
      <Head>
        <title>Vascomm Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <div className='row justify-content-center'>
          <div className='col-md-4 col-md-offset-4 border border-secondary mt-3 mb-3'>
            <br></br>
            <h4 className='text-center'>Register</h4>
            <hr></hr>
            <a href='/' className='left ms-2'><Image alt='Back' src={Back} /></a>
            <br></br>
            <br></br>
            <div className='form-group'>
                <label for='username' className='left'>Username</label>
                <input type='text' className='form-control' name='username' onChange={e => setUsername(e.target.value)} />
            </div>
            <div className='form-group'>
                <label for='password' className='left'>Password</label>
                <input type='password' className='form-control' name='password' onChange={e => setPassword(e.target.value)} />
            </div>
            <div className='form-group'>
                <label for='foto' className='left'>Foto</label>
                <input type='file' accept='image/*' className='form-control' name='foto' onChange={e => setFoto(e.target.files[0])} />
            </div>
            <br></br>
            {failMessage !== '' && <p className='text-danger text-center'>{failMessage}</p>}
            {successMessage !== '' && <p className='text-success text-center'>{successMessage}</p>}
            <div className='form-group text-center'>
                <button className='btn btn-block btn-primary' onClick={register}>Register</button>
            </div>
            <br></br>
          </div>
          <a href='/auth/login' className='text-center'>Already have an account? Login here</a>
        </div>
      </div>
    </>
  )
}
