import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useState, useEffect } from 'react'
import { useCookies } from 'react-cookie'
import axios from 'axios'
import { useRouter } from "next/router";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [user, setUser] = useState([]);
  const [cookies, setCookies, removeCookies] = useCookies();
  const router = useRouter();

  const logout = async (e) => {
    e.preventDefault();
    removeCookies("vascomm_api_key");
    router.push("/")
  }

  const getUser = async (e) => {
    axios.get(`${process.env.NEXT_PUBLIC_VASCOMM_TEST_API}/user`, {
        headers: { 'Authorization': 'Bearer ' + cookies.vascomm_api_key}
    }).then(response => {
        setUser(response.data);
    })
  }

  const verify = async (username) => {
    axios.get(`${process.env.NEXT_PUBLIC_VASCOMM_TEST_API}/user/verify/${username}`, {
        headers: { 'Authorization': 'Bearer ' + cookies.vascomm_api_key}
    }).then(response => {
        getUser();
    })
  }

  useEffect(() => {
    if (cookies.vascomm_api_key) {
      if (cookies.vascomm_api_key.split('-')[1] === '1') {
        getUser();
      } else {
        router.push("/")
      }
    } else {
        router.push("/")
    }
  }, [])

  return (
    <>
      <Head>
        <title>Vascomm Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <div className='row justify-content-center'>
          <div className='col-md-6 col-md-offset-4 border border-secondary mt-3 mb-3'>
            <br></br>
            <h4 className='text-center'>List User</h4>
            <hr></hr>
            <div className='text-center'>
                <button className='btn btn-danger' onClick={logout}>Log Out</button>
            </div>
            <hr></hr>
            <table className='table table-secondary text-center mt-3'>
                <thead>
                    <tr>
                        <th>Nama</th>
                        <th>Foto</th>
                        <th></th>
                    </tr>
                </thead>
                {user.map((val) => {
                    return (
                        <tbody>
                            <tr>
                                <td>{val.username}</td>
                                <td><Image width={125} height={100} src={`${process.env.NEXT_PUBLIC_VASCOMM_TEST_API}/${val.foto}`} /></td>
                                <td>
                                    {val.approved == 0 && <button className='btn btn-primary' onClick={e => {
                                        e.preventDefault();
                                        verify(val.username);
                                    }}>Verifikasi</button>}
                                    {val.approved == 1 && <button className='btn btn-warning' disabled>Verified</button>}
                                </td>
                            </tr>
                        </tbody>
                    )
                })}
            </table>
          </div>
        </div>
      </div>
    </>
  )
}
