import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { useCookies } from 'react-cookie'
import axios from 'axios'
import { useRouter } from "next/router";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [username, setUsername] = useState();
  const [foto, setFoto] = useState();
  const [cookies, setCookies, removeCookies] = useCookies();
  const router = useRouter();

  const logout = async (e) => {
    e.preventDefault();
    removeCookies("vascomm_api_key");
  }

  useEffect(() => {
    if (cookies.vascomm_api_key) {
      if (cookies.vascomm_api_key.split('-')[1] === '0') {
        axios.get(`${process.env.NEXT_PUBLIC_VASCOMM_TEST_API}/user/${cookies.vascomm_api_key.split('-')[0]}`, {
          headers: { 'Authorization': 'Bearer ' + cookies.vascomm_api_key}
        }).then(response => {
          setUsername(response.data.username);
          setFoto(response.data.foto);
        })
      } else {
        router.push("/admin")
      }
    }
  }, [])

  return (
    <>
      <Head>
        <title>Vascomm Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <div className='row justify-content-center'>
          <div className='col-md-6 col-md-offset-4 border border-secondary mt-3 mb-3'>
            <br></br>
            <h4 className='text-center'>Home</h4>
            <hr></hr>
            {!cookies.vascomm_api_key && <div className='text-center'>
                <a href='/auth/login'><button className='btn btn-block btn-success'>Login</button></a>
                <a href='/auth/register'><button className='btn btn-block btn-success ms-3'>Register</button></a>
            </div>}
            {cookies.vascomm_api_key && <div className='text-center'>
                <p>{username}</p>
                <Image width={250} height={200} src={`${process.env.NEXT_PUBLIC_VASCOMM_TEST_API}/${foto}`}/>
                <br></br>
                <br></br>
                <button className='btn btn-danger' onClick={logout}>Log Out</button>
            </div>}
            <hr></hr>
            <h5 className='text-center'>List Produk</h5>
            <table className='table table-secondary text-center mt-3'>
              <thead>
                  <tr>
                      <th>Nama</th>
                      <th>Jumlah</th>
                      <th>Harga</th>
                  </tr>
              </thead>
              <tbody>
                  <tr>
                      <td>Contoh Nama 1</td>
                      <td>Contoh Jumlah 1</td>
                      <td>Contoh Harga 1</td>
                  </tr>
                  <tr>
                      <td>Contoh Nama 2</td>
                      <td>Contoh Jumlah 2</td>
                      <td>Contoh Harga 2</td>
                  </tr>
                  <tr>
                      <td>Contoh Nama 3</td>
                      <td>Contoh Jumlah 3</td>
                      <td>Contoh Harga 3</td>
                  </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  )
}
